### PR TITLE
Allow specifying start_cell on upload and refactor df2gspread using gspread addr methods

### PR DESCRIPTION
**Pull request by jasonqng**
This PR allows a user to override the default starting spot in the sheet to place the dataframe. The pre-existing behavior is to always put it starting at A1. This PR preserves this default setting, but now a user can pass in a `start_cell` parameter to insert the dataframe at a chosen location. It supports multi-char and multi-digit cells, so it can handle something like `start_cell = 'AF100'`. Furthermore, if there are not enough cells or if the location does not exist in the sheet, the sheet will add the necessary rows and/or cols to update it.

This PR will have merge conflicts with https://github.com/maybelinot/df2gspread/pull/16 and will have to be tweaked to deal with cases where a user requests a sheet sized to match the df as well as a starting spot, and since this is more of a nice to have feature as opposed to a more crucial one like https://github.com/maybelinot/df2gspread/pull/16 (at least in my case), I'd recommend reviewing that one first and I'll deal with the merge conflicts and updates in this PR after. But feel free to make comments about the general usability and implementation of this PR at any point. It works as is right now.

(Also made some minor tweaks to the comments, correcting some typos. And I refactored df2gspread so it uses gspread's native `get_addr_int` (e.g., AA = 27) and `get_int_addr` methods (vice versa) so you don't have to code your own custom solution: 
* https://gspread.readthedocs.io/en/latest/#gspread.Worksheet.get_addr_int
* https://gspread.readthedocs.io/en/latest/#gspread.Worksheet.get_int_addr

Hopefully this makes the code a bit cleaner and easier to expand on in the future.)

### CODE REVIEW

**Comment by jasonqng** [comment]
@maybelinot In the latest commit, I refactored df2gspread so it uses gspread's native get_addr_int (e.g., AA = 27) and get_int_addr functions (vice versa) so you don't have to code your own custom solution: 
* https://gspread.readthedocs.io/en/latest/#gspread.Worksheet.get_addr_int
* https://gspread.readthedocs.io/en/latest/#gspread.Worksheet.get_int_addr

Hopefully this makes the code a bit cleaner and easier to expand on in the future.

**Comment by jasonqng** [comment]
Tests (for some reason, the `test_client_secrets_credentials` always fails, even on master):

```
➜  df2gspread git:(specify-start-cell) py.test tests/ -v
============================= test session starts ==============================
platform darwin -- Python 2.7.10, pytest-2.9.2, py-1.4.31, pluggy-0.3.1 -- /usr/bin/python
cachedir: .cache
rootdir: /Users/jpersonal/Projects/df2gspread, inifile:
collected 8 items

tests/test_credentials.py::test_client_secrets_credentials xfail
tests/test_df2gspread.py::test_global_import PASSED
tests/test_df2gspread.py::test_version_check PASSED
tests/test_df2gspread.py::test_spreadsheet_invalid_file_id PASSED
tests/test_df2gspread.py::test_worksheet_invalid_name PASSED
tests/test_df2gspread.py::test_worksheet PASSED
tests/test_df2gspread.py::test_big_worksheet PASSED
tests/test_df2gspread.py::test_delete_file PASSED

===================== 7 passed, 1 xfailed in 87.81 seconds =====================
```

**Comment by maybelinot** [comment]
Nice!
Like this feature.. wanted to implement it for a long time :)
btw, it would be also helpful to add the same functionality to gspread2df(start_cell and df_size) to make it back compatible..

I have implemented some custom solutions, which was covered by gspread later. Good thing that I can remove some of them. Good work!

Feel free to add `df_size` functionality to this PR.

**Comment by maybelinot** [comment]
`test_client_secrets_credentials` always fails because you need `service_credentials` look at `tests/conftest.py`. Was added here #9

**Comment by maybelinot** [comment]
@jasonqng I would suggest to implement `start_cell` feature for `download()` function before, because missing of this feature breaks functionality of `row_names` and `col_names` in `download()`.

**Comment by jasonqng** [comment]
Sounds good! I added some tests for start_cell. Yes, please review this one and if it looks good, merge it first before I update and fix the other df_size PR.

**Comment by maybelinot** [comment]
Well done! 
Manually merged with master.

**Pull request closed without merging**
